import type { PagedList } from '../types/common';
import type { MapInfo, MapInsertInfo, MapUpdateInfo } from '../types/map';
import { API_URL, getHeaders, handleApiResponse, toQuery } from './apiHelpers';

interface MapServiceConfig {
  onUnauthorized?: () => void;
}

/** Map Service — maps of a campaign (instances of map models). */
class MapService {
  private config: MapServiceConfig;

  constructor(config: MapServiceConfig = {}) {
    this.config = config;
  }

  private async handleResponse<T>(response: Response): Promise<T> {
    return handleApiResponse<T>(response, this.config.onUnauthorized);
  }

  /** Lists the non-deleted maps of a campaign (master or approved participant). */
  async listByCampaign(campaignId: number, page = 1, pageSize = 20): Promise<PagedList<MapInfo>> {
    const response = await fetch(`${API_URL}/api/campaign/${campaignId}/map${toQuery({ page, pageSize })}`, {
      headers: getHeaders(true),
    });
    return this.handleResponse<PagedList<MapInfo>>(response);
  }

  /** One campaign map (master or approved participant). */
  async getById(id: number): Promise<MapInfo> {
    const response = await fetch(`${API_URL}/api/map/${id}`, { headers: getHeaders(true) });
    return this.handleResponse<MapInfo>(response);
  }

  /** Adds a map model to a campaign (only the master); the name is generated by the server. */
  async create(data: MapInsertInfo): Promise<MapInfo> {
    const response = await fetch(`${API_URL}/api/map`, {
      method: 'POST', headers: getHeaders(true), body: JSON.stringify(data),
    });
    return this.handleResponse<MapInfo>(response);
  }

  /** Master: renames a campaign map or archives/reactivates it. */
  async update(id: number, data: MapUpdateInfo): Promise<MapInfo> {
    const response = await fetch(`${API_URL}/api/map/${id}`, {
      method: 'PUT', headers: getHeaders(true), body: JSON.stringify(data),
    });
    return this.handleResponse<MapInfo>(response);
  }

  /** Master: deletes a campaign map (soft delete). */
  async remove(id: number): Promise<void> {
    const response = await fetch(`${API_URL}/api/map/${id}`, { method: 'DELETE', headers: getHeaders(true) });
    return this.handleResponse<void>(response);
  }
}

export const mapService = new MapService();
export default MapService;
