<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SimpleTabletopMap.Domain\SimpleTabletopMap.Domain.csproj" />
    <ProjectReference Include="..\SimpleTabletopMap.Infra\SimpleTabletopMap.Infra.csproj" />
    <ProjectReference Include="..\SimpleTabletopMap.DTO\SimpleTabletopMap.DTO.csproj" />
    <ProjectReference Include="..\SimpleTabletopMap.Infra.Interfaces\SimpleTabletopMap.Infra.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.31" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
