// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpleTabletopMap.Infra.Context;

#nullable disable

namespace SimpleTabletopMap.Infra.Migrations
{
    [DbContext(typeof(SimpleTabletopMapContext))]
    [Migration("20260925212828_AddCampaignCharacterVitals")]
    partial class AddCampaignCharacterVitals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpleTabletopMap.Domain.Models.Campaign", b =>
                {
                    b.Property<long>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CampaignId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<bool>("Open")
                        .HasColumnType("boolean")
                        .HasColumnName("open");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("CampaignId")
                        .HasName("campaigns_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("SimpleTabletopMap.Domain.Models.CampaignCharacter", b =>
                {
                    b.Property<long>("CampaignCharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_character_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CampaignCharacterId"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentEnergy")
                        .HasColumnType("integer")
                        .HasColumnName("current_energy");

                    b.Property<int>("CurrentLife")
                        .HasColumnType("integer")
                        .HasColumnName("current_life");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CampaignCharacterId")
                        .HasName("campaign_characters_pkey");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CampaignId", "CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_characters_campaign_character");

                    b.ToTable("campaign_characters", (string)null);
                });

            modelBuilder.Entity("SimpleTabletopMap.Domain.Models.Character", b =>
                {
                    b.Property<long>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CharacterId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Energy")
                        .HasColumnType("integer")
                        .HasColumnName("energy");

                    b.Property<string>("Image")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("image");

                    b.Property<int>("Life")
                        .HasColumnType("integer")
                        .HasColumnName("life");

                    b.Property<int>("Move")
                        .HasColumnType("integer")
                        .HasColumnName("move");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<string>("Sheet")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("sheet");

                    b.Property<string>("Status")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("CharacterId")
                        .HasName("characters_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("SimpleTabletopMap.Domain.Models.Map", b =>
                {
                    b.Property<long>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("map_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("MapId"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("MapModelId")
                        .HasColumnType("bigint")
                        .HasColumnName("map_model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("MapId")
                        .HasName("maps_pkey");

                    b.HasIndex("MapModelId");

                    b.HasIndex("UserId");

                    b.HasIndex("CampaignId", "MapModelId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_maps_campaign_model_sequence");

                    b.ToTable("maps", (string)null);
                });

            modelBuilder.Entity("SimpleTabletopMap.Domain.Models.MapModel", b =>
                {
                    b.Property<long>("MapModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("map_model_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("MapModelId"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("GridHeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20)
                        .HasColumnName("grid_height");

                    b.Property<int>("GridWidth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20)
                        .HasColumnName("grid_width");

                    b.Property<string>("Image")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("image");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("integer")
                        .HasColumnName("image_height");

                    b.Property<int>("ImageLeft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("image_left");

                    b.Property<int>("ImageTop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("image_top");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("integer")
                        .HasColumnName("image_width");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("MapModelId")
                        .HasName("map_models_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("map_models", (string)null);
                });

            modelBuilder.Entity("SimpleTabletopMap.Domain.Models.MapToken", b =>
                {
                    b.Property<long>("MapTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("map_token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("MapTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Energy")
                        .HasColumnType("integer")
                        .HasColumnName("energy");

                    b.Property<int>("Life")
                        .HasColumnType("integer")
                        .HasColumnName("life");

                    b.Property<int>("Look")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("look");

                    b.Property<long>("MapId")
                        .HasColumnType("bigint")
                        .HasColumnName("map_id");

                    b.Property<int>("Move")
                        .HasColumnType("integer")
                        .HasColumnName("move");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<string>("Sheet")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("sheet");

                    b.Property<string>("Status")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("status");

                    b.Property<long>("TokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    b.Property<int>("TokenType")
                        .HasColumnType("integer")
                        .HasColumnName("token_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.HasKey("MapTokenId")
                        .HasName("map_tokens_pkey");

                    b.HasIndex("MapId");

                    b.HasIndex("TokenId");

                    b.ToTable("map_tokens", (string)null);
                });

            modelBuilder.Entity("SimpleTabletopMap.Domain.Models.Token", b =>
                {
                    b.Property<long>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DownImage")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("down_image");

                    b.Property<int?>("DownSpace")
                        .HasColumnType("integer")
                        .HasColumnName("down_space");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<string>("UpImage")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("up_image");

                    b.Property<int>("UpSpace")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("up_space");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("tokens_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("tokens", (string)null);
                });

            modelBuilder.Entity("SimpleTabletopMap.Domain.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SimpleTabletopMap.Domain.Models.Campaign", b =>
                {
                    b.HasOne("SimpleTabletopMap.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_campaign");
                });

            modelBuilder.Entity("SimpleTabletopMap.Domain.Models.CampaignCharacter", b =>
                {
                    b.HasOne("SimpleTabletopMap.Domain.Models.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_campaign_character");

                    b.HasOne("SimpleTabletopMap.Domain.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .IsRequired()
                        .HasConstraintName("fk_character_campaign_character");
                });

            modelBuilder.Entity("SimpleTabletopMap.Domain.Models.Character", b =>
                {
                    b.HasOne("SimpleTabletopMap.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_character");
                });

            modelBuilder.Entity("SimpleTabletopMap.Domain.Models.Map", b =>
                {
                    b.HasOne("SimpleTabletopMap.Domain.Models.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_map");

                    b.HasOne("SimpleTabletopMap.Domain.Models.MapModel", null)
                        .WithMany()
                        .HasForeignKey("MapModelId")
                        .IsRequired()
                        .HasConstraintName("fk_map_model_map");

                    b.HasOne("SimpleTabletopMap.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_map");
                });

            modelBuilder.Entity("SimpleTabletopMap.Domain.Models.MapModel", b =>
                {
                    b.HasOne("SimpleTabletopMap.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_map_model");
                });

            modelBuilder.Entity("SimpleTabletopMap.Domain.Models.MapToken", b =>
                {
                    b.HasOne("SimpleTabletopMap.Domain.Models.Map", null)
                        .WithMany()
                        .HasForeignKey("MapId")
                        .IsRequired()
                        .HasConstraintName("fk_map_map_token");

                    b.HasOne("SimpleTabletopMap.Domain.Models.Token", null)
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .IsRequired()
                        .HasConstraintName("fk_token_map_token");
                });

            modelBuilder.Entity("SimpleTabletopMap.Domain.Models.Token", b =>
                {
                    b.HasOne("SimpleTabletopMap.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_token");
                });
#pragma warning restore 612, 618
        }
    }
}
