// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Roll6.Infra.Context;

#nullable disable

namespace Roll6.Infra.Migrations
{
    [DbContext(typeof(Roll6Context))]
    partial class Roll6ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Roll6.Domain.Models.Campaign", b =>
                {
                    b.Property<long>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CampaignId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentTurn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("current_turn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<bool>("Open")
                        .HasColumnType("boolean")
                        .HasColumnName("open");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("CampaignId")
                        .HasName("campaigns_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("Roll6.Domain.Models.CampaignCharacter", b =>
                {
                    b.Property<long>("CampaignCharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_character_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CampaignCharacterId"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    b.Property<string>("CharacterStatus")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("character_status");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentEnergy")
                        .HasColumnType("integer")
                        .HasColumnName("current_energy");

                    b.Property<int>("CurrentLife")
                        .HasColumnType("integer")
                        .HasColumnName("current_life");

                    b.Property<string>("Sheet")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("sheet");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CampaignCharacterId")
                        .HasName("campaign_characters_pkey");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CampaignId", "CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_characters_campaign_character");

                    b.ToTable("campaign_characters", (string)null);
                });

            modelBuilder.Entity("Roll6.Domain.Models.CampaignNpc", b =>
                {
                    b.Property<long>("CampaignNpcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_npc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CampaignNpcId"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("NpcId")
                        .HasColumnType("bigint")
                        .HasColumnName("npc_id");

                    b.HasKey("CampaignNpcId")
                        .HasName("campaign_npcs_pkey");

                    b.HasIndex("NpcId");

                    b.HasIndex("CampaignId", "NpcId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_npcs_campaign_npc");

                    b.ToTable("campaign_npcs", (string)null);
                });

            modelBuilder.Entity("Roll6.Domain.Models.Character", b =>
                {
                    b.Property<long>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CharacterId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Energy")
                        .HasColumnType("integer")
                        .HasColumnName("energy");

                    b.Property<string>("Image")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("image");

                    b.Property<int>("Life")
                        .HasColumnType("integer")
                        .HasColumnName("life");

                    b.Property<int>("Move")
                        .HasColumnType("integer")
                        .HasColumnName("move");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<string>("Sheet")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("sheet");

                    b.Property<long?>("TokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("CharacterId")
                        .HasName("characters_pkey");

                    b.HasIndex("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("Roll6.Domain.Models.Map", b =>
                {
                    b.Property<long>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("map_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("MapId"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("MapModelId")
                        .HasColumnType("bigint")
                        .HasColumnName("map_model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("MapId")
                        .HasName("maps_pkey");

                    b.HasIndex("MapModelId");

                    b.HasIndex("UserId");

                    b.HasIndex("CampaignId", "MapModelId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_maps_campaign_model_sequence");

                    b.ToTable("maps", (string)null);
                });

            modelBuilder.Entity("Roll6.Domain.Models.MapModel", b =>
                {
                    b.Property<long>("MapModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("map_model_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("MapModelId"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("GridHeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20)
                        .HasColumnName("grid_height");

                    b.Property<int>("GridWidth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20)
                        .HasColumnName("grid_width");

                    b.Property<string>("Image")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("image");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("integer")
                        .HasColumnName("image_height");

                    b.Property<int>("ImageLeft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("image_left");

                    b.Property<int>("ImageTop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("image_top");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("integer")
                        .HasColumnName("image_width");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("MapModelId")
                        .HasName("map_models_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("map_models", (string)null);
                });

            modelBuilder.Entity("Roll6.Domain.Models.MapNpc", b =>
                {
                    b.Property<long>("MapNpcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("map_npc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("MapNpcId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Energy")
                        .HasColumnType("integer")
                        .HasColumnName("energy");

                    b.Property<int>("Life")
                        .HasColumnType("integer")
                        .HasColumnName("life");

                    b.Property<long>("MapId")
                        .HasColumnType("bigint")
                        .HasColumnName("map_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<long>("NpcId")
                        .HasColumnType("bigint")
                        .HasColumnName("npc_id");

                    b.Property<string>("Status")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MapNpcId")
                        .HasName("map_npcs_pkey");

                    b.HasIndex("MapId");

                    b.HasIndex("NpcId");

                    b.ToTable("map_npcs", (string)null);
                });

            modelBuilder.Entity("Roll6.Domain.Models.MapToken", b =>
                {
                    b.Property<long>("MapTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("map_token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("MapTokenId"));

                    b.Property<long?>("CampaignCharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_character_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Energy")
                        .HasColumnType("integer")
                        .HasColumnName("energy");

                    b.Property<int>("Life")
                        .HasColumnType("integer")
                        .HasColumnName("life");

                    b.Property<int>("Look")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("look");

                    b.Property<long>("MapId")
                        .HasColumnType("bigint")
                        .HasColumnName("map_id");

                    b.Property<long?>("MapNpcId")
                        .HasColumnType("bigint")
                        .HasColumnName("map_npc_id");

                    b.Property<int>("Move")
                        .HasColumnType("integer")
                        .HasColumnName("move");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<string>("Sheet")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("sheet");

                    b.Property<string>("Status")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("status");

                    b.Property<long>("TokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    b.Property<int>("TokenType")
                        .HasColumnType("integer")
                        .HasColumnName("token_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.HasKey("MapTokenId")
                        .HasName("map_tokens_pkey");

                    b.HasIndex("CampaignCharacterId");

                    b.HasIndex("MapNpcId")
                        .IsUnique()
                        .HasDatabaseName("ix_map_tokens_map_npc")
                        .HasFilter("map_npc_id IS NOT NULL");

                    b.HasIndex("TokenId");

                    b.HasIndex("MapId", "CampaignCharacterId")
                        .IsUnique()
                        .HasDatabaseName("ix_map_tokens_map_campaign_character")
                        .HasFilter("campaign_character_id IS NOT NULL");

                    b.ToTable("map_tokens", (string)null);
                });

            modelBuilder.Entity("Roll6.Domain.Models.Npc", b =>
                {
                    b.Property<long>("NpcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("npc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("NpcId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Energy")
                        .HasColumnType("integer")
                        .HasColumnName("energy");

                    b.Property<string>("Image")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("image");

                    b.Property<int>("Life")
                        .HasColumnType("integer")
                        .HasColumnName("life");

                    b.Property<int>("Move")
                        .HasColumnType("integer")
                        .HasColumnName("move");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<string>("Sheet")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("sheet");

                    b.Property<long>("TokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("NpcId")
                        .HasName("npcs_pkey");

                    b.HasIndex("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("npcs", (string)null);
                });

            modelBuilder.Entity("Roll6.Domain.Models.Token", b =>
                {
                    b.Property<long>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DownImage")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("down_image");

                    b.Property<int?>("DownSpace")
                        .HasColumnType("integer")
                        .HasColumnName("down_space");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<string>("UpImage")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("up_image");

                    b.Property<int>("UpSpace")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("up_space");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("tokens_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("tokens", (string)null);
                });

            modelBuilder.Entity("Roll6.Domain.Models.Turn", b =>
                {
                    b.Property<long>("TurnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("turn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("TurnId"));

                    b.Property<int?>("BeforeLook")
                        .HasColumnType("integer")
                        .HasColumnName("before_look");

                    b.Property<int?>("BeforeX")
                        .HasColumnType("integer")
                        .HasColumnName("before_x");

                    b.Property<int?>("BeforeY")
                        .HasColumnType("integer")
                        .HasColumnName("before_y");

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<long?>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int?>("Look")
                        .HasColumnType("integer")
                        .HasColumnName("look");

                    b.Property<long?>("MapId")
                        .HasColumnType("bigint")
                        .HasColumnName("map_id");

                    b.Property<long?>("MapNpcId")
                        .HasColumnType("bigint")
                        .HasColumnName("map_npc_id");

                    b.Property<long?>("NpcId")
                        .HasColumnType("bigint")
                        .HasColumnName("npc_id");

                    b.Property<int>("TurnNo")
                        .HasColumnType("integer")
                        .HasColumnName("turn_no");

                    b.Property<int>("TurnType")
                        .HasColumnType("integer")
                        .HasColumnName("turn_type");

                    b.Property<int?>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int?>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.HasKey("TurnId")
                        .HasName("turns_pkey");

                    b.HasIndex("CharacterId");

                    b.HasIndex("MapId");

                    b.HasIndex("MapNpcId");

                    b.HasIndex("NpcId");

                    b.HasIndex("CampaignId", "TurnNo")
                        .HasDatabaseName("ix_turns_campaign_turn");

                    b.ToTable("turns", (string)null);
                });

            modelBuilder.Entity("Roll6.Domain.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Roll6.Domain.Models.Campaign", b =>
                {
                    b.HasOne("Roll6.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_campaign");
                });

            modelBuilder.Entity("Roll6.Domain.Models.CampaignCharacter", b =>
                {
                    b.HasOne("Roll6.Domain.Models.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_campaign_character");

                    b.HasOne("Roll6.Domain.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .IsRequired()
                        .HasConstraintName("fk_character_campaign_character");
                });

            modelBuilder.Entity("Roll6.Domain.Models.CampaignNpc", b =>
                {
                    b.HasOne("Roll6.Domain.Models.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_campaign_npc");

                    b.HasOne("Roll6.Domain.Models.Npc", null)
                        .WithMany()
                        .HasForeignKey("NpcId")
                        .IsRequired()
                        .HasConstraintName("fk_npc_campaign_npc");
                });

            modelBuilder.Entity("Roll6.Domain.Models.Character", b =>
                {
                    b.HasOne("Roll6.Domain.Models.Token", null)
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .HasConstraintName("fk_token_character");

                    b.HasOne("Roll6.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_character");
                });

            modelBuilder.Entity("Roll6.Domain.Models.Map", b =>
                {
                    b.HasOne("Roll6.Domain.Models.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_map");

                    b.HasOne("Roll6.Domain.Models.MapModel", null)
                        .WithMany()
                        .HasForeignKey("MapModelId")
                        .IsRequired()
                        .HasConstraintName("fk_map_model_map");

                    b.HasOne("Roll6.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_map");
                });

            modelBuilder.Entity("Roll6.Domain.Models.MapModel", b =>
                {
                    b.HasOne("Roll6.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_map_model");
                });

            modelBuilder.Entity("Roll6.Domain.Models.MapNpc", b =>
                {
                    b.HasOne("Roll6.Domain.Models.Map", null)
                        .WithMany()
                        .HasForeignKey("MapId")
                        .IsRequired()
                        .HasConstraintName("fk_map_map_npc");

                    b.HasOne("Roll6.Domain.Models.Npc", null)
                        .WithMany()
                        .HasForeignKey("NpcId")
                        .IsRequired()
                        .HasConstraintName("fk_npc_map_npc");
                });

            modelBuilder.Entity("Roll6.Domain.Models.MapToken", b =>
                {
                    b.HasOne("Roll6.Domain.Models.CampaignCharacter", null)
                        .WithMany()
                        .HasForeignKey("CampaignCharacterId")
                        .HasConstraintName("fk_campaign_character_map_token");

                    b.HasOne("Roll6.Domain.Models.Map", null)
                        .WithMany()
                        .HasForeignKey("MapId")
                        .IsRequired()
                        .HasConstraintName("fk_map_map_token");

                    b.HasOne("Roll6.Domain.Models.MapNpc", null)
                        .WithMany()
                        .HasForeignKey("MapNpcId")
                        .HasConstraintName("fk_map_npc_map_token");

                    b.HasOne("Roll6.Domain.Models.Token", null)
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .IsRequired()
                        .HasConstraintName("fk_token_map_token");
                });

            modelBuilder.Entity("Roll6.Domain.Models.Npc", b =>
                {
                    b.HasOne("Roll6.Domain.Models.Token", null)
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .IsRequired()
                        .HasConstraintName("fk_token_npc");

                    b.HasOne("Roll6.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_npc");
                });

            modelBuilder.Entity("Roll6.Domain.Models.Token", b =>
                {
                    b.HasOne("Roll6.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_token");
                });

            modelBuilder.Entity("Roll6.Domain.Models.Turn", b =>
                {
                    b.HasOne("Roll6.Domain.Models.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .IsRequired()
                        .HasConstraintName("fk_campaign_turn");

                    b.HasOne("Roll6.Domain.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .HasConstraintName("fk_character_turn");

                    b.HasOne("Roll6.Domain.Models.Map", null)
                        .WithMany()
                        .HasForeignKey("MapId")
                        .HasConstraintName("fk_map_turn");

                    b.HasOne("Roll6.Domain.Models.MapNpc", null)
                        .WithMany()
                        .HasForeignKey("MapNpcId")
                        .HasConstraintName("fk_map_npc_turn");

                    b.HasOne("Roll6.Domain.Models.Npc", null)
                        .WithMany()
                        .HasForeignKey("NpcId")
                        .HasConstraintName("fk_npc_turn");
                });
#pragma warning restore 612, 618
        }
    }
}
